config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'map/index'
  get 'area/:code', :to => 'map#index', :as => "map_area"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, :only => [:show]

  root to: 'map#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  def password_required?
   new_record? ? false : super
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :restaurants
end

app/models/restaurant.rb
# -*- coding: utf-8 -*-
class Restaurant < ApplicationRecord
  geocoded_by :address
  # after_validation :geocode, if: :address_changed?
  after_validation :geocode, if: ->(obj){ (obj.latitude.blank? || obj.longitude.blank?) && obj.address.present? && obj.address_changed? }

  after_validation :fill_prefecture

  has_many :urls
  belongs_to :prefecture
  belongs_to :yakisoba_type

  accepts_nested_attributes_for :urls, :allow_destroy => true
 
  # 住所から自動的に都道府県レコードを関連付ける
  def fill_prefecture
    if prefecture.blank?
      Prefecture.all.each do |pref|
        if address.start_with?(pref.name)
          self.prefecture = pref
          break
        end
      end
    end
  end

  def address_combined
    [address, address2].join(" ")
  end
end

app/models/url.rb
class Url < ApplicationRecord
  belongs_to :url_type
end

app/models/url_type.rb
class UrlType < ApplicationRecord
end

app/models/yakisoba_type.rb
class YakisobaType < ApplicationRecord
  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @prefectures = Prefecture.order(:id)

    if q = params[:q]
      @restaurants = Restaurant.where('name LIKE ?', '%'+q+'%').order(:id => "desc")
    elsif code = params[:code]
      @prefecture = Prefecture.where(:code => code).first
      if @prefecture
        @restaurants = @prefecture.restaurants.order(:id => "desc")
      end
    else
      @restaurants = Restaurant.order(:id => "desc")
    end
    @hash = Gmaps4rails.build_markers(@restaurants) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "map/infowindow", locals: { :restaurant => restaurant})
      marker.picture(url: view_context.asset_path("orange-dot.png"),
                     width: 32,
                     height: 32,
                     )
      marker.json({title: restaurant.name})
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
    @hash = Gmaps4rails.build_markers([@restaurant]) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
      marker.infowindow render_to_string(partial: "map/infowindow", locals: { :restaurant => restaurant})
      marker.picture(url: view_context.asset_path("orange-dot.png"),
                     width: 32,
                     height: 32,
                     )
      marker.json({title: restaurant.name})
    end
  end
end

app/helpers/application_helper.rb
# -*- coding: utf-8 -*-
module ApplicationHelper
  # Google Map APIのscriptタグを出力
  def google_map_script_tag
    key = Rails.env.production? ? Yakisoba::Application.config.google_map_api_key : ""
    url = "//maps.google.com/maps/api/js?v=3&amp;libraries=geometry"
    if key.present?
      url += "&key=" + key
    end
    content_tag :script, "", :src => url, :type => "text/javascript"
  end

  # Google Static Map APIのimgタグを出力
  def google_static_map_image_tag(restaurant)
    key = Rails.env.production? ? Yakisoba::Application.config.google_static_map_api_key : ""
    url = "http://maps.google.com/maps/api/staticmap?size=640x320&sensor=false&zoom=16&markers=#{restaurant.latitude}%2C#{restaurant.longitude}"
    if key.present?
      url += "&key=" + key
    end
    image_tag url
  end

  # 都道府県別店舗ページのリンク
  def area_link_tags(prefectures)
    content_tag :div, :class => "callout prefectures-list" do
      prefectures.collect{|pref|
         pref.restaurants.present? ?
	   link_to(pref.name, map_area_path(pref.code)) :
           pref.name
       }.join(" ").html_safe 
    end
  end


  # デフォルトのmetaタグ
  def default_meta_tags
  {
    site:       Yakisoba::Application.config.application_name,
    description: '日本やきそばマップは、日本全国で美味しいやきそばが食べられるお店をまとめた、やきそばファンのための情報サイトです。',
    keywords:    ['やきそば', '焼きそば', 'ヤキソバ'],
    separator:   "|",
    reverse: true,
    og: { 
      title: :title,
      description: '日本やきそばマップは、日本全国で美味しいやきそばが食べられるお店をまとめた、やきそばファンのための情報サイトです。',
    }
  }
  end

  def nl2br(str)
    return sanitize(str).gsub("\n", '<br>').html_safe
  end
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= display_meta_tags(default_meta_tags) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= google_map_script_tag %>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js" type="text/javascript"></script>
  </head>
  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="menu-text"><%= link_to Yakisoba::Application.config.application_name, root_path %></li>
          <li class="hide-for-small-only"><input type="search" placeholder="店名で検索" value="<%= params[:q] %>" class="search1"></li>
          <li class="hide-for-small-only"><button type="button" class="button button1">検索</button></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
           <li class="menu-text description"><%= '日本やきそばマップは、日本全国で美味しいやきそばが食べられるお店をまとめた、やきそばファンのための情報サイトです。' %></li>
        </ul>
      </div>
    </div>
    <div class="search-mobile row">
      <div class="small-9 columns show-for-small-only">
        <input type="search" placeholder="店名で検索" value="<%= params[:q] %>" class="search2">
      </div>
      <div class="small-3 columns show-for-small-only">
        <button type="button" class="button button2">検索</button>
      </div>
    </div>
    <%= yield %>
    <% if Rails.env.production? %>
      <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89482381-1', 'auto');
  ga('send', 'pageview');

      </script>
    <% end %>
    <footer class="footer">
      Copyright © 2017 SATO Osamu. All rights reserved.
    </footer>
  </body>
</html>

app/views/map/_infowindow.html.erb
<%=
  content_tag(:div) do
    concat(content_tag(:p, :class => :name) do 
      restaurant.name
    end)
    concat(content_tag(:p, :class => :address) do
      restaurant.address_combined
    end)
    concat(content_tag(:p, :class => :phone) do
      restaurant.phone
    end)
    concat(content_tag(:p, :class => :detail) do
      link_to "詳細", restaurant_path(restaurant)
    end)
  end
%>

app/views/map/index.html.erb
<% 
  if @prefecture 
    set_meta_tags title: [title, "#{@prefecture.name}の店舗一覧"],
                 keywords: default_meta_tags[:keywords] << @prefecture.name,
                 description: "#{@prefecture.name}のやきそば情報を紹介します。" + default_meta_tags[:description],
                 og: default_meta_tags[:og].merge(:description => "#{@prefecture.name}のやきそば情報を紹介します。" + default_meta_tags[:og][:description])
  end
%>
<div class="row">
  <div class="medium-8 small-12 columns hide-for-small-only">
    <% if @prefecture %>
      <h4><%= @prefecture.name %>のやきそば店舗一覧</h4>
    <% end %>
    <div style='width:100%;padding:10px;'>
      <div id="map" style='width:100%;height:420px;'></div>
    </div>
    <h5>都道府県で絞り込み</h5>
    <%= area_link_tags(@prefectures) %>
  </div>
  <div class="medium-4 small-0 columns">
    <div class="ad">
      <% if Rails.env.production? %>
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- トップ画面右下部 -->
        <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="ca-pub-8686579472251964"
           data-ad-slot="3848660192"
           data-ad-format="auto"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
      <% end %>
    </div>
    <div class="restaurant-list">
      <% @restaurants.each do |restaurant| %>
      <div class="restaurant-item">
        <%= link_to restaurant_path(restaurant) do %>
        <div class="restaurant-name"><%= restaurant.name %></div>
        <div class="restaurant-address"><%= restaurant.address_combined %></div>
        <div class="restaurant-phone"><%= restaurant.phone %></div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map', detect_location: true}}, function(){
      if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(function(position){
          var marker = handler.addMarker({
            lat: position.coords.latitude,
            lng: position.coords.longitude,
            picture: {
              url: "<%= asset_path "green.png" %>",
              width:  36,
              height: 36
            }
          });
          handler.map.centerOn(marker);
        });
      }
      markers = handler.addMarkers(<%=raw @hash.to_json %>);

      /*
       * 都道府県別ページ以外は、前回の中心座標・ズームを
       * Cookieから読み込んで使用する
       */
      force_center = <%= @prefecture ? "true" : "false" %>; 
      if (Cookies.get("lat") == null || Cookies.get("lng") == null || Cookies.get("zoom") == null || force_center == true) {
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();

        center = handler.getMap().getCenter();
        Cookies.set("lat", center.lat());
        Cookies.set("lng", center.lng());
        Cookies.set("zoom", handler.getMap().getZoom());
      } else {
        handler.getMap().setCenter(new google.maps.LatLng(Cookies.get("lat"), Cookies.get("lng")));
        handler.getMap().setZoom(parseInt(Cookies.get("zoom")));
      }

      /*
       * 中心座標とズームを変更時に、その値をCookieに保存
       */
      google.maps.event.addListener(handler.getMap(), 'center_changed', 
        function() {
          center = handler.getMap().getCenter();
          Cookies.set("lat", center.lat());
          Cookies.set("lng", center.lng());
        });
      google.maps.event.addListener(handler.getMap(), 'zoom_changed',
        function() {
          Cookies.set("zoom", handler.getMap().getZoom());
        });
    });
</script>

app/views/restaurants/_form.html.erb
<%= form_for(restaurant) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.latitude %></td>
        <td><%= restaurant.longitude %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% 
  keywords = default_meta_tags[:keywords] << @restaurant.name
  keywords << @restaurant.prefecture.name if @restaurant.prefecture.present?
  keywords << @restaurant.yakisoba_type.name if @restaurant.yakisoba_type.present?
  set_meta_tags title: [title, @restaurant.name],
                 keywords: keywords,
                 description: "#{@restaurant.name}のやきそば情報を紹介します。" + default_meta_tags[:description],
                 og: default_meta_tags[:og].merge(:description => "#{@restaurant.name}のやきそば情報を紹介します。" + default_meta_tags[:og][:description])
%>
<div class="row">
  <div class="large-6 columns restaurant-detail">
    <h3><%= @restaurant.name %></h3>
    <table>
      <tr>
        <th><%= Restaurant.human_attribute_name(:name) %></th>
        <td><%= @restaurant.name %></td>
      </tr>
      <tr>
        <th><%= Restaurant.human_attribute_name(:address_combined) %></th>
        <td><%= @restaurant.address_combined %></td>
      </tr>
      <% if @restaurant.phone.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:phone) %></th>
          <td><%= @restaurant.phone || '-' %></td>
        </tr>
      <% end %>
      <% if @restaurant.open_and_close.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:open_and_close) %></th>
          <td><%= nl2br(@restaurant.open_and_close) %></td>
        </tr>
      <% end %>
      <% if @restaurant.regular_holiday.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:regular_holiday) %></th>
          <td><%= nl2br(@restaurant.regular_holiday) %></td>
        </tr>
      <% end %>
      <% if @restaurant.seats.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:seats) %></th>
          <td><%= nl2br(@restaurant.seats) %></td>
        </tr>
      <% end %>
      <% if @restaurant.access.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:access) %></th>
          <td><%= nl2br(@restaurant.access) %></td>
        </tr>
      <% end %>
      <% if @restaurant.urls.present? %>
        <tr>
          <th><%= Restaurant.human_attribute_name(:url) %></th>
          <td><%= @restaurant.urls.collect{|u|
                  name = (u.url_type ? u.url_type.name : u.title) || u.url
                  link_to(name, u.url, {:target => "blank"})
                }.join("</br>").html_safe
           %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="large-6 columns hide-for-small-only">
    <div style='width:100%;padding:5px;'>
      <div id="map" style='width:100%;height:500px;'></div>
    </div>
  </div>
  <div class="large-6 columns show-for-small-only">
    <%= google_static_map_image_tag(@restaurant) %>
  </div>
</div>
<div class="row">
  <div class="large-12 columns show-for-small-only">
  <%= link_to "地図をアプリで開く", "http://maps.apple.com/?q=#{@restaurant.latitude},#{@restaurant.longitude}", :class => "button map-button" %>
  </div>
</div>

</div>
<div class="row">
  <div class="large-12 columns">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- 詳細画面下部レスポンシブ -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-8686579472251964"
         data-ad-slot="8255180190"
         data-ad-format="auto"></ins>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
</div>
<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(16);
    });
</script>